apiVersion: v1
kind: Pod
metadata:
  name: volume
  namespace: nimmi
spec:
  containers:
  - name: my-container
    image: nginx
    volumeMounts:
    - name: gcs-creds
      mountPath: /etc/gcs-creds
      readOnly: true
    - name: gcs-data
      mountPath: /data
    command: ["/bin/bash", "-c", "echo 'Hello, world!' > /data/gcs-test.txt && /usr/bin/gsutil cp /data/gcs-test.txt gs://bucketng1/ && nginx -g 'daemon off;'"]
  volumes:
  - name: gcs-creds
    secret:
      secretName: gcs-creds
  - name: gcs-data
    emptyDir: {}
