apiVersion: v1
kind: Pod
metadata:
    name: volumeexample
    namespace: nimmi
spec:
  containers:
  - name: my-container
    image: my-image
    volumeMounts:
    - name: bucketng1
      mountPath: /data
  volumes:
  - name: bucketng1
    gcePersistentDisk:
      pdName: my-gcs-bucket
      fsType: ext4